[package]
name = "conditional-deps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(target_os = "linux")'.dependencies]
nix = { version = "0.26.2", features = ["time", "process"] }
